# File:
#	./mk-ca-directories.yml
# Functionality:
#	- Used to create directory structure and initial files for a each caname in the list
#	- Will loop through canames listed in ca-info.yml creating directory trees for each
#
# usage:
#	 ansible-playbook -i hosts mk-ca-directories.yml 
# dependancies:
#	./vars/ca-info.yml
#	./cars/ca-secrets.yml
# Make the following directories and files:
#  <toplevelpath>/<ca_name>CA/<ca_name>CA/
#  <toplevelpath>/<ca_name>CA/newcerts/
#  <toplevelpath>/<ca_name>/index.txt  #touch to create file
#  <toplevelpath>/<ca_name>/index.txt.attr  #set to unique_subject = no for last CA so csr's can be signed multiple times
#                                           #set to unique_subject = yes for oterh CA's since it is normal not to resign the same CSR multiple times
#  <toplevelpath>/<ca_name>/serial       #echo 1000 > serial to create the file
#
# Below may be in different playbook
#  <toplevelpath>/<ca_name>/<ca_name>.cnf
#  <toplevelpath>/<ca_name>/<ca_name>Key.pem
#  <toplevelpath>/<ca_name>/<ca_name>Csr.pem
#  <toplevelpath>/<ca_name>/<ca_name>Cert.pem



- hosts: all
  
  tasks:

    - include_vars: ./vars/ca-info.yml
    - include_vars: ./vars/ca-secrets.yml

    - name: "Ping server."
      action: ping

    - name: "Create CA Directories"
      file:
        path: "{{ ca_top_dir }}/{{ item.caname }}"
        state: directory
      file:
        path: "{{ ca_top_dir }}/{{ item.caname }}/newcerts"
        state: directory
      with_items: "{{canames}}"

    - name: " Create index.txt files"
      file:
        path: "{{ ca_top_dir }}/{{ item.caname }}/index.txt"
        state: touch
      with_items: "{{canames}}"

    - name: "Create index.txt.attr file"
      copy:
        dest: "{{ ca_top_dir }}/{{ item.caname }}/index.txt.attr"
        content:  |
          {{ item.indexattr }}
      with_items: "{{canames}}"

    - name: "Create serial file"
      copy:
        dest: "{{ ca_top_dir }}/{{ item.caname }}/serial"
        content:  |
          {{ item.serialstart }}
      with_items: "{{canames}}"

